version: '3.8'

services:
  axia-webapi:
    image: axia-webapi:latest
    container_name: axia-webapi
    build:
      context: .
      dockerfile: src/Axia.WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    restart: always
